# Laboratorium 9

## Wybrane zagadnienia algebry liniowej, faktoryzacja

In [40]:
using(LinearAlgebra)
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedMatrix{T}) where T in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\dense.jl:1241
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\dense.jl:1315
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\dense.jl:1316
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\triangular.jl:2216
[5] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\lu.jl:555
[6] factorize(D::Diagonal) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\diagonal.jl:121
[7] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\bidiag.jl:882
[8] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\ldlt.jl:167
[9] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\SparseArrays\src\linalg.jl:1599
[10] factorize(A::Union{Hermitian{ComplexF64, var"#s832"}, Hermitian{Float64, var"#s832"}, Symmetric{Float64, var"#s832"}} where var"#s832"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\SparseArrays\src\linalg.jl:1629
[11] factorize(A::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S}) in LinearAlgebra at C:\Users\basia\AppData\Local\Programs\Julia-1.6.0\share\julia\stdlib\v1.6\LinearAlgebra\src\symmetric.jl:637

Zadania
Zadanie 1 (1pkt)

Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x. Nastepnie rozwiąż równanie Ax=b trzema metodami:

- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy od drugiego wywołania !

Zadanie 2 (1pkt)

Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium). Porównaj wyniki z tymi otrzymanymi poprzednio.

Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

- tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

- uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

- zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254

### Zadanie 1

In [41]:
using Statistics

In [44]:
x = rand(1000)
A = rand(1000, 1000)
b = A*x
x

1000-element Vector{Float64}:
 0.5049585985669289
 0.8092757083332709
 0.6372650339946078
 0.865262853210349
 0.1318326610147651
 0.38936600007841915
 0.40714702338361297
 0.31005412490494666
 0.22773225307835854
 0.4990858380331211
 0.04281875536865121
 0.9909162991304434
 0.21953971148484897
 ⋮
 0.7205056662455727
 0.21722709122789485
 0.3111189512928587
 0.13069385450577897
 0.5901526504883825
 0.7841160275155741
 0.6766674298274973
 0.7428657646569614
 0.5355457955399427
 0.6798695888013755
 0.9478715451922832
 0.5836776969995705

In [45]:
x_inv = []
x_slash = []
x_fact = []

iters = 50
time_inv = zeros(iters);
time_slash = zeros(iters);
time_fact = zeros(iters);

In [46]:
function invA()
    global x_inv = inv(A)*b
end

function slash()
    global x_slash = A\b
end

function factorizeA()
    global x_fact = factorize(A)\b
end

factorizeA (generic function with 1 method)

In [47]:
function measure_time()
    # inv(A)*b
    for i = -10:iters
        if i > 0
            time_inv[i] = @elapsed invA()
        end
    end
    
    # A\b
    for i = -10:iters
        if i > 0
            time_slash[i] = @elapsed slash()
        end
    end   
    
    # factorize(A)\b
    for i = -10:iters
        if i > 0
            time_fact[i] = @elapsed factorizeA()
        end
    end
    println("TIMES (MEAN):")
    println("inv(A)*b:\t", mean(time_inv))
    println("A\\b:\t\t", mean(time_slash))
    println("factorize(A)\\b:\t", mean(time_fact))
end

measure_time (generic function with 1 method)

In [48]:
measure_time()

TIMES (MEAN):
inv(A)*b:	0.230682688
A\b:		0.09489047599999999
factorize(A)\b:	0.083514012


In [49]:
diff_1 = x - x_inv
diff_2 = x - x_slash
diff_3 = x - x_fact

function vec_len(vec)
    return sqrt(dot(vec, vec))
end

println("PRECISION (vector length):")
println("inv(A)*b:\t", vec_len(diff_1))
println("A\\b:\t\t", vec_len(diff_2))
println("factorize(A)\\b:\t", vec_len(diff_3))

PRECISION (vector length):
inv(A)*b:	3.665430380039976e-11
A\b:		2.6078253846699892e-11
factorize(A)\b:	2.6078253846699892e-11


### Zadanie 2

In [67]:
using CSV
using DataFrames
using Plots
using Statistics
using Polynomials

In [61]:
data=CSV.read("results.csv", DataFrame)
data

100×5 DataFrame
 Row │ size   sample_nr  naive_mult_time  better_mult_time  BLAS_time 
     │ Int64  Int64      Int64            Int64             Int64     
─────┼────────────────────────────────────────────────────────────────
   1 │    50          1                0                 0          0
   2 │    50          2                0                 0          0
   3 │    50          3                0                 1          0
   4 │    50          4                0                 0          0
   5 │    50          5                0                 0          0
   6 │    50          6                0                 0          0
   7 │    50          7                1                 0          0
   8 │    50          8                0                 0          0
   9 │    50          9                0                 0          0
  10 │    50         10                0                 0          0
  11 │   100          1                0                 1          0
  ⋮  │   ⋮        ⋮             ⋮                ⋮              ⋮
  91 │   500          1               57                44          8
  92 │   500          2               57                44          8
  93 │   500          3               58                44          8
  94 │   500          4               59                45          8
  95 │   500          5               62                50         10
  96 │   500          6               63                44          8
  97 │   500          7               67                45          8
  98 │   500          8               60                44          9
  99 │   500          9               59                44          8
 100 │   500         10               63                49          9
                                                       79 rows omitted

In [62]:
data_grouped = combine(groupby(data, :size), "naive_mult_time" => mean)

10×2 DataFrame
 Row │ size   naive_mult_time_mean 
     │ Int64  Float64              
─────┼─────────────────────────────
   1 │    50                   0.1
   2 │   100                   0.3
   3 │   150                   1.5
   4 │   200                   3.2
   5 │   250                   6.3
   6 │   300                  11.1
   7 │   350                  19.1
   8 │   400                  28.3
   9 │   450                  41.8
  10 │   500                  60.5

In [68]:
x = data_grouped[:,1]
y = data_grouped[:,2]
fit_poly_3=fit(x, y, 3)

Polynomial(-1.1299999999999681 + 0.027282439782439362*x - 0.00017258741258741113*x^2 + 7.261849261849247e-7*x^3)

#### 1. Tworzymy macierz A na podstawie $(x_{i}, y_{i})$

In [71]:
A=zeros(10,4)
A[:,1]=x.^3
A[:,2]=x.^2
A[:,3]=x
A[:,4]=ones(10)
A

10×4 Matrix{Float64}:
 125000.0         2500.0   50.0  1.0
      1.0e6      10000.0  100.0  1.0
      3.375e6    22500.0  150.0  1.0
      8.0e6      40000.0  200.0  1.0
      1.5625e7   62500.0  250.0  1.0
      2.7e7      90000.0  300.0  1.0
      4.2875e7  122500.0  350.0  1.0
      6.4e7     160000.0  400.0  1.0
      9.1125e7  202500.0  450.0  1.0
      1.25e8    250000.0  500.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A

In [73]:
# QR Factorization
AF=factorize(A)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.000710955  -0.0339428  -0.378124   …  -0.0960535  -0.207478   -0.282764
 -0.00568764   -0.118713   -0.518293      -0.0634765   0.220747    0.678134
 -0.0191958    -0.228722   -0.48057        0.497687    0.316026   -0.144889
 -0.0455012    -0.338383   -0.325016      -0.168339   -0.252272   -0.533898
 -0.0888694    -0.422107   -0.111694      -0.128003   -0.0471947   0.0717579
 -0.153566     -0.454308    0.0993344  …  -0.218805   -0.0870957   0.158386
 -0.243858     -0.409397    0.248007      -0.273819   -0.128876    0.1746
 -0.364009     -0.261787    0.274262       0.723252   -0.183053    0.0511814
 -0.518287      0.0141099   0.118037      -0.211292    0.739858   -0.281087
 -0.710955      0.443882   -0.280731      -0.0611514  -0.370663    0.108578
R factor:
4×4 Matrix{Float64}:
 -1.7582e8      -3.92492e5  -900.532  -2.15064
  0.0       -65432.4        -377.086  -1.80937
  0.0       

In [74]:
# Orthogonal check
Transpose(AF.Q)*AF.Q

10×10 Matrix{Float64}:
  1.0           0.0          -1.11022e-16  …   0.0          -5.55112e-17
  0.0           1.0           2.77556e-17      2.77556e-17   1.59595e-16
 -1.11022e-16   2.77556e-17   1.0             -1.38778e-17   1.49186e-16
  2.498e-16    -2.77556e-17   1.11022e-16      8.32667e-17   2.67147e-16
  2.77556e-17  -3.1225e-17    2.08167e-17      3.46945e-18   9.28077e-17
  1.38778e-17   4.85723e-17  -1.52656e-16  …   2.77556e-17  -1.21431e-17
  2.08167e-17  -6.245e-17    -1.2837e-16       4.16334e-17   6.93889e-18
  4.16334e-17   7.28584e-17  -8.32667e-17     -2.42861e-17  -2.77556e-17
  0.0           2.77556e-17  -1.38778e-17      1.0           9.71445e-17
 -5.55112e-17   1.59595e-16   1.49186e-16      9.71445e-17   1.0

In [121]:
# Solve
solution1 = AF.R\((Transpose(AF.Q)*y)[1:4])

4-element Vector{Float64}:
  7.261849261849285e-7
 -0.00017258741258741487
  0.02728243978244043
 -1.1300000000000523

In [122]:
# Equivalent to
solution2 = A\y

4-element Vector{Float64}:
  7.261849261849268e-7
 -0.00017258741258741316
  0.027282439782439966
 -1.1300000000000152

In [127]:
function digitss(vec, digs)
    return [round(xs, digits=digs) for xs in vec]
end

function compare_results(sol1, sol2, sol3, digits)
    s1 = digitss(sol1, digits)
    s2 = digitss(sol2, digits)
    s3 = digitss(sol3, digits)
    for i in eachindex(s1)
        if s1[i] != s2[i] || s2[i] != s3[i] || s1[i] != s3[i]
            return false
        end
    end
    return true
end

compare_results (generic function with 1 method)

In [120]:
solution3 = reverse(coeffs(fit_poly_3))

4-element Vector{Float64}:
  7.261849261849247e-7
 -0.00017258741258741113
  0.027282439782439362
 -1.1299999999999681

In [133]:
compare_results(solution1, solution2, solution3, 12)

true

In [134]:
compare_results(solution1, solution2, solution3, 13)

false

#### Uzyskane trzema metodami wartości współczynników wielomianu aproksymującego są takie same z dokładnością do 12 miesjc po przecinku.

### Zadanie 3